### ISSUE TITLE
Cache epubcheck when testing

### ISSUE THREAD

**Issue by DarkerStar** [DarkerStar/epub-makefile#17]
### What new feature would you like to see?

Currently, `epubcheck` has to be downloaded and decompressed every time the testing workflow is run. This isn’t *too* expensive, but it’s still wasteful.

It would be better if every version of `epubcheck` used could be cached.

### Do you have any ideas for how this feature might be implemented?

It should be possible to use [the standard cache action](https://github.com/actions/cache). It might look something like this:

```yaml
- name: Cache epubcheck
  uses: actions/cache@v3
  id: cache-epubcheck
  with:
    path: test/epubcheck-[0-9].[0-9].[0-9]
  enableCrossOsArchive: false
```
